version: '3.8'

services:
  # Application Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL:-mongodb://mongodb:27017/alterego_db}
      - DB_NAME=${DB_NAME:-alterego_db}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-Micael}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Micael123}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    restart: unless-stopped
    networks:
      - dokploy-network
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.alterego.rule=Host(`app.alteregopatrimoine.com`)"
        - "traefik.http.routers.alterego.entrypoints=web,websecure"
        - "traefik.http.routers.alterego.tls.certresolver=letsencrypt"
        - "traefik.http.services.alterego.loadbalancer.server.port=3000"
        - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true
