version: '3.8'

services:
  # Application Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017/alterego_db
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-Micael}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Micael123}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - alterego-network

  # Base de données MongoDB
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    restart: unless-stopped
    networks:
      - alterego-network
    command: mongod --quiet --logpath /dev/null

volumes:
  mongodb-data:
    driver: local
  mongodb-config:
    driver: local

networks:
  alterego-network:
    driver: bridge
